// <Auto-Generated/>
using System.Collections.Immutable;
using FluentWorkflow.Interface;

namespace TemplateNamespace;

/// <summary>
/// <see cref="TemplateWorkflow"/> 的阶段定义
/// </summary>
public static class TemplateWorkflowStages
{
    /// <summary>
    /// 有序的阶段名称列表
    /// </summary>
    public static ImmutableArray<string> OrderedStages { get; }

    /// <summary>
    /// 有序的阶段ID列表
    /// </summary>
    public static ImmutableArray<string> OrderedStageIds { get; }

    /// <summary>
    /// 去重的阶段列表
    /// </summary>
    public static ImmutableHashSet<string> Stages { get; }

    /// <summary>
    /// 去重的阶段ID列表
    /// </summary>
    public static ImmutableHashSet<string> StageIds { get; }

    /// <summary>
    /// 阶段 Stage1CAUK
    /// </summary>
    public const string Stage1CAUK = "TemplateWorkflow.Stage.Stage1CAUK";

    /// <summary>
    /// 阶段 Stage2BPTG
    /// </summary>
    public const string Stage2BPTG = "TemplateWorkflow.Stage.Stage2BPTG";

    /// <summary>
    /// 阶段 Stage3AWBN
    /// </summary>
    public const string Stage3AWBN = "TemplateWorkflow.Stage.Stage3AWBN";

    /// <summary>
    /// 阶段 Completion
    /// </summary>
    public const string Completion = "TemplateWorkflow.Stage.Completion";

    /// <summary>
    /// 阶段 Failure
    /// </summary>
    public const string Failure = "TemplateWorkflow.Stage.Failure";

    /// <inheritdoc cref="TemplateWorkflowStages"/>
    static TemplateWorkflowStages()
    {
        OrderedStageIds = ImmutableArray.Create(Stage1CAUK, Stage2BPTG, Stage3AWBN);
        OrderedStages = ImmutableArray.Create(nameof(Stage1CAUK), nameof(Stage2BPTG), nameof(Stage3AWBN));

        StageIds = ImmutableHashSet.Create(StringComparer.Ordinal, Stage1CAUK, Stage2BPTG, Stage3AWBN, Completion, Failure);
        Stages = ImmutableHashSet.Create(StringComparer.Ordinal, nameof(Stage1CAUK), nameof(Stage2BPTG), nameof(Stage3AWBN), nameof(Completion), nameof(Failure));
    }
}

/// <summary>
/// 标记接口 - 标记属于工作流程 <see cref="TemplateWorkflow"/>
/// </summary>
public interface ITemplateWorkflow { }

/// <summary>
/// 标记接口 - 标记属于工作流程 <see cref="TemplateWorkflow"/> 的阶段 <see cref="TemplateWorkflowStages.Stage1CAUK"/>
/// </summary>
public interface ITemplateWorkflowStage1CAUKStage : IWorkflowStage, ITemplateWorkflow { }

/// <summary>
/// 标记接口 - 标记属于工作流程 <see cref="TemplateWorkflow"/> 的阶段 <see cref="TemplateWorkflowStages.Stage2BPTG"/>
/// </summary>
public interface ITemplateWorkflowStage2BPTGStage : IWorkflowStage, ITemplateWorkflow { }

/// <summary>
/// 标记接口 - 标记属于工作流程 <see cref="TemplateWorkflow"/> 的阶段 <see cref="TemplateWorkflowStages.Stage3AWBN"/>
/// </summary>
public interface ITemplateWorkflowStage3AWBNStage : IWorkflowStage, ITemplateWorkflow { }
