// <Auto-Generated/>

using System.ComponentModel;
using FluentWorkflow;

namespace TemplateNamespace;

[WorkflowDefine(1, "Template", "Stage1CAUK", "Stage2BPTG", "Stage3AWBN")]
[WorkflowContextTypedProperty<int>("UserId", "注释UserId", false)]
[WorkflowContextTypedProperty<string>("Name", "注释Name", false)]
[WorkflowContextTypedProperty<int>("Age", "", true)]
[WorkflowContextTypedProperty<string>("Address", "", true)]
[WorkflowContextTypedProperty<TemplateWorkflowTestInfo>("TestInfo", "", true)]
public sealed partial class TemplateWorkflowDeclaration : TemplateWorkflowDeclarationBase, IWorkflowDeclaration
{
}

/// <summary>
/// <see cref="TemplateWorkflowDeclaration"/> 的辅助定义基类
/// </summary>
[EditorBrowsable(EditorBrowsableState.Never)]
public abstract class TemplateWorkflowDeclarationBase : IWorkflowDeclaration
{
    #region Internal 方法

    /// <summary>
    /// 声明工作流程上下文
    /// </summary>
    /// <param name="declarator"></param>
    internal abstract void DeclareContext(IWorkflowContextDeclarator declarator);

    /// <summary>
    /// 声明工作流程
    /// </summary>
    /// <param name="declarator"></param>
    internal abstract void DeclareWorkflow(IWorkflowDeclarator declarator);

    #endregion Internal 方法
}
