// <Auto-Generated/>

using FluentWorkflow;

namespace TemplateNamespace;

[WorkflowDefine(2, "Template", "Stage1CAUK", "Stage2BPTG", "Stage3AWBN")]
[WorkflowContextTypedProperty<int>("UserId", "注释UserId")]
[WorkflowContextTypedProperty<string>("Name", "注释Name")]
[WorkflowContextTypedProperty<int>("Age", "")]
[WorkflowContextTypedProperty<string>("Address", "")]
[WorkflowContextTypedProperty<TemplateWorkflowTestInfo>("TestInfo", "")]
public sealed partial class TemplateWorkflowDeclaration : TemplateWorkflowDeclarationBase, IWorkflowDeclaration
{
}
