// <Auto-Generated/>
using System.ComponentModel;
using FluentWorkflow;
using FluentWorkflow.Extensions;
using FluentWorkflow.Interface;
using TemplateNamespace.Message;

namespace TemplateNamespace
{
    partial class TemplateWorkflow
    {
        /// <summary>
        /// <see cref="TemplateWorkflow"/> 状态机基类
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Never)]
        public abstract partial class TemplateWorkflowStateMachineBase
            : WorkflowStateMachine<ITemplateWorkflow>
            , ITemplateWorkflow
        {
            private readonly IWorkflowMessageDispatcher _messageDispatcher;

            /// <inheritdoc cref="TemplateWorkflowContext"/>
            protected readonly TemplateWorkflowContext TypedContext;

            /// <summary>
            /// 工作流程 <see cref="TemplateWorkflow"/> 实例
            /// </summary>
            protected readonly TemplateWorkflow Workflow;

            /// <inheritdoc cref="TemplateWorkflowStateMachineBase"/>
            public TemplateWorkflowStateMachineBase(TemplateWorkflow workflow, IWorkflowMessageDispatcher messageDispatcher, IServiceProvider serviceProvider)
                : base(workflow.Context, messageDispatcher, serviceProvider)
            {
                Workflow = workflow ?? throw new ArgumentNullException(nameof(workflow));
                TypedContext = workflow.Context;
                _messageDispatcher = messageDispatcher ?? throw new ArgumentNullException(nameof(messageDispatcher));
            }

            /// <inheritdoc/>
            public override async Task MoveNextAsync(CancellationToken cancellationToken)
            {
                var currentStage = Context.Stage;
                if (string.IsNullOrWhiteSpace(currentStage))
                {
                    currentStage = TemplateWorkflowStages.Stage1CAUK;
                    Context.SetCurrentStage(currentStage);
                }

                using var singleCaller = new ScopePublishStageMessageSingleCaller(MessageDispatcher);

                switch (currentStage)
                {
                    case TemplateWorkflowStages.Stage1CAUK:
                        {
                            var stageMessage = new TemplateWorkflowStage1CAUKStageMessage(TypedContext);
                            stageMessage.Context.SetCurrentStageState(WorkflowStageState.Created);
                            await Workflow.OnStage1CAUKAsync(stageMessage, singleCaller.PublishStageMessageAsync, cancellationToken);
                            return;
                        }
                    case TemplateWorkflowStages.Stage2BPTG:
                        {
                            var stageMessage = new TemplateWorkflowStage2BPTGStageMessage(TypedContext);
                            stageMessage.Context.SetCurrentStageState(WorkflowStageState.Created);
                            await Workflow.OnStage2BPTGAsync(stageMessage, singleCaller.PublishStageMessageAsync, cancellationToken);
                            return;
                        }
                    case TemplateWorkflowStages.Stage3AWBN:
                        {
                            var stageMessage = new TemplateWorkflowStage3AWBNStageMessage(TypedContext);
                            stageMessage.Context.SetCurrentStageState(WorkflowStageState.Created);
                            await Workflow.OnStage3AWBNAsync(stageMessage, singleCaller.PublishStageMessageAsync, cancellationToken);
                            return;
                        }
                    case TemplateWorkflowStages.Failure:
                        {
                            Context.TryGetFailureMessage(out var failureMessage);
                            var finishedMessage = new TemplateWorkflowFinishedMessage(TypedContext, false, failureMessage ?? "Unknown error");
                            await _messageDispatcher.PublishAsync(finishedMessage, cancellationToken);
                            return;
                        }
                    case TemplateWorkflowStages.Completion:
                        {
                            TypedContext.SetCurrentStageState(WorkflowStageState.Created);
                            await Workflow.OnCompletionAsync(TypedContext, cancellationToken);

                            if (Context.Flag.HasFlag(WorkflowFlag.IsBeenAwaited)
                                || !Context.Flag.HasFlag(WorkflowFlag.NotNotifyOnFinish))
                            {
                                var finishedMessage = new TemplateWorkflowFinishedMessage(TypedContext, true, "SUCCESS");
                                await _messageDispatcher.PublishAsync(finishedMessage, cancellationToken);
                            }
                            return;
                        }
                }
                throw new WorkflowInvalidOperationException($"未知的阶段：{currentStage}");
            }

            /// <inheritdoc/>
            public override Task<bool> IsCompletedAsync(CancellationToken cancellationToken)
            {
                var currentStage = Context.Stage;
                var result = string.Equals(TemplateWorkflowStages.Completion, currentStage);

                return Task.FromResult(result);
            }

            /// <summary>
            /// 使用完成消息设置阶段完成
            /// </summary>
            /// <param name="stageCompletedMessage"></param>
            /// <param name="cancellationToken"></param>
            /// <returns>是否执行后续代码</returns>
            /// <exception cref="WorkflowInvalidOperationException"></exception>
            internal virtual async Task<bool> SetStageCompletedAsync(ITemplateWorkflowStageCompletedMessage stageCompletedMessage, CancellationToken cancellationToken)
            {
                //设置上下文阶段状态，以使 OnStageCompletedAsync 中获取到的上下文当前阶段状态为已结束
                //如果在 OnStageCompletedAsync 中挂起上下文，在恢复流程时使用此值确定应当再次调用 SetStageCompletedAsync 而不是 MoveNextAsync
                stageCompletedMessage.Context.SetCurrentStageState(WorkflowStageState.Finished);

                using var singleCaller = new ScopeOnStageCompletedSingleCaller(this);

                var stageCompletedTask = stageCompletedMessage switch
                {
                    TemplateWorkflowStage1CAUKStageCompletedMessage stage1CA5CStageCompletedMessage => Workflow.OnStage1CAUKCompletedAsync(stage1CA5CStageCompletedMessage, singleCaller.OnStageCompletedAsync, cancellationToken),
                    TemplateWorkflowStage2BPTGStageCompletedMessage stage2B74EStageCompletedMessage => Workflow.OnStage2BPTGCompletedAsync(stage2B74EStageCompletedMessage, singleCaller.OnStageCompletedAsync, cancellationToken),
                    TemplateWorkflowStage3AWBNStageCompletedMessage stage3A2B4StageCompletedMessage => Workflow.OnStage3AWBNCompletedAsync(stage3A2B4StageCompletedMessage, singleCaller.OnStageCompletedAsync, cancellationToken),
                    _ => throw new WorkflowInvalidOperationException($"未知的阶段完成消息：{stageCompletedMessage}"),
                };

                await stageCompletedTask;

                if (singleCaller.HasInvoked)
                {
                    SetCurrentStageToNext();
                    return true;
                }
                return false;

                void SetCurrentStageToNext()
                {
                    var nextStage = stageCompletedMessage.Stage switch
                    {
                        TemplateWorkflowStages.Stage1CAUK => TemplateWorkflowStages.Stage2BPTG,
                        TemplateWorkflowStages.Stage2BPTG => TemplateWorkflowStages.Stage3AWBN,
                        TemplateWorkflowStages.Stage3AWBN => TemplateWorkflowStages.Completion,
                        _ => throw new WorkflowInvalidOperationException($"未知的阶段完成消息：{stageCompletedMessage}"),
                    };

                    Context.SetCurrentStage(nextStage);
                }
            }

            /// <summary>
            /// 使用失败消息设置流程失败
            /// </summary>
            /// <param name="failureMessage"></param>
            /// <param name="cancellationToken"></param>
            /// <returns>是否执行后续代码</returns>
            /// <exception cref="WorkflowInvalidOperationException"></exception>
            internal virtual async Task<bool> SetFailedAsync(ITemplateWorkflowFailureMessage failureMessage, CancellationToken cancellationToken)
            {
                if (failureMessage is not TemplateWorkflowFailureMessage typedFailureMessage)
                {
                    throw new WorkflowInvalidOperationException($"未知的失败消息：{failureMessage}");
                }

                using var singleCaller = new ScopeOnFailedSingleCaller(this);

                await Workflow.OnFailedAsync(typedFailureMessage, singleCaller.OnFailedAsync, cancellationToken);

                return singleCaller.HasInvoked;
            }

            /// <inheritdoc/>
            protected override async Task OnFailedAsync<TFailureMessage>(TFailureMessage failureMessage, CancellationToken cancellationToken)
            {
                await base.OnFailedAsync(failureMessage, cancellationToken);

                Context.SetCurrentStage(TemplateWorkflowStages.Failure);
            }
        }
    }
}

namespace TemplateNamespace.Internal
{
    /// <summary>
    /// <see cref="TemplateWorkflow"/> 的状态机
    /// </summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public sealed partial class TemplateWorkflowStateMachine : TemplateWorkflow.TemplateWorkflowStateMachineBase
    {
        /// <inheritdoc/>
        public TemplateWorkflowStateMachine(TemplateWorkflow workflow, IWorkflowMessageDispatcher messageDispatcher, IServiceProvider serviceProvider) : base(workflow, messageDispatcher, serviceProvider)
        {
        }
    }
}
