// <Auto-Generated/>

using System.ComponentModel;
using FluentWorkflow;

namespace TemplateNamespace;

/// <summary>
/// <see cref="TemplateWorkflowDeclaration"/> 的辅助定义基类
/// </summary>
[EditorBrowsable(EditorBrowsableState.Never)]
public abstract class TemplateWorkflowDeclarationBase : IWorkflowDeclaration
{
    #region Internal 方法

    /// <summary>
    /// 声明工作流程上下文
    /// </summary>
    /// <param name="declarator"></param>
    internal abstract void DeclareContext(IWorkflowContextDeclarator declarator);

    /// <summary>
    /// 声明工作流程
    /// </summary>
    /// <param name="declarator"></param>
    internal abstract void DeclareWorkflow(IWorkflowDeclarator declarator);

    #endregion Internal 方法
}

partial class TemplateWorkflowDeclaration : TemplateWorkflowDeclarationBase 
{
}
