// <Auto-Generated/>
using System.Collections.Immutable;
using System.ComponentModel;
using FluentWorkflow.Abstractions;

namespace TemplateNamespace.Template;

/// <summary>
/// <see cref="TemplateWorkflow"/> 的阶段定义
/// <br/><br/>工作流程阶段顺序：<br/><see cref="TemplateStages.Stage1CAUK"/> -><br/> <see cref="TemplateStages.Stage2BPTG"/> -><br/> <see cref="TemplateStages.Stage3AWBN"/>
/// </summary>
public static class TemplateStages
{
    /// <summary>
    /// 有序的阶段名称列表
    /// </summary>
    public static ImmutableArray<string> OrderedStages { get; }

    /// <summary>
    /// 有序的阶段ID列表
    /// </summary>
    public static ImmutableArray<string> OrderedStageIds { get; }

    /// <summary>
    /// 去重的阶段列表
    /// </summary>
    public static ImmutableHashSet<string> Stages { get; }

    /// <summary>
    /// 去重的阶段ID列表
    /// </summary>
    public static ImmutableHashSet<string> StageIds { get; }

    /// <summary>
    /// 阶段 Stage1CAUK
    /// </summary>
    public const string Stage1CAUK = "Template.Stage.Stage1CAUK";

    /// <summary>
    /// 阶段 Stage2BPTG
    /// </summary>
    public const string Stage2BPTG = "Template.Stage.Stage2BPTG";

    /// <summary>
    /// 阶段 Stage3AWBN
    /// </summary>
    public const string Stage3AWBN = "Template.Stage.Stage3AWBN";

    /// <summary>
    /// 阶段 Completion
    /// </summary>
    public const string Completion = "Template.Stage.@Completion";

    /// <summary>
    /// 阶段 Failure
    /// </summary>
    public const string Failure = "Template.Stage.@Failure";

    /// <inheritdoc cref="TemplateStages"/>
    static TemplateStages()
    {
        OrderedStageIds = ImmutableArray.Create(Stage1CAUK, Stage2BPTG, Stage3AWBN);
        OrderedStages = ImmutableArray.Create(nameof(Stage1CAUK), nameof(Stage2BPTG), nameof(Stage3AWBN));

        StageIds = ImmutableHashSet.Create(StringComparer.Ordinal, Stage1CAUK, Stage2BPTG, Stage3AWBN, Completion, Failure);
        Stages = ImmutableHashSet.Create(StringComparer.Ordinal, nameof(Stage1CAUK), nameof(Stage2BPTG), nameof(Stage3AWBN), nameof(Completion), nameof(Failure));
    }
}

/// <summary>
/// 标记接口 - 标记属于工作流程 <see cref="TemplateWorkflow"/>
/// </summary>
[EditorBrowsable(EditorBrowsableState.Advanced)]
public interface ITemplateWorkflow { }

/// <summary>
/// 标记接口 - 标记属于工作流程 <see cref="TemplateWorkflow"/> 的阶段 <see cref="TemplateStages.Stage1CAUK"/>
/// </summary>
[EditorBrowsable(EditorBrowsableState.Advanced)]
public interface IStageStage1CAUK : IWorkflowStage, ITemplateWorkflow { }

/// <summary>
/// 标记接口 - 标记属于工作流程 <see cref="TemplateWorkflow"/> 的阶段 <see cref="TemplateStages.Stage2BPTG"/>
/// </summary>
[EditorBrowsable(EditorBrowsableState.Advanced)]
public interface IStageStage2BPTG : IWorkflowStage, ITemplateWorkflow { }

/// <summary>
/// 标记接口 - 标记属于工作流程 <see cref="TemplateWorkflow"/> 的阶段 <see cref="TemplateStages.Stage3AWBN"/>
/// </summary>
[EditorBrowsable(EditorBrowsableState.Advanced)]
public interface IStageStage3AWBN : IWorkflowStage, ITemplateWorkflow { }
