// <Auto-Generated/>

using DotNetCore.CAP;
using TemplateNamespace.Message;

namespace TemplateNamespace.Handler;

partial class TemplateWorkflowResultObserver : ICapSubscribe
{
    /// <summary>
    /// 处理消息 <inheritdoc cref="TemplateWorkflowFinishedMessage.EventName"/>
    /// </summary>
    /// <param name="message"></param>
    /// <param name="cancellationToken"></param>
    /// <returns></returns>
    [CapSubscribe(TemplateWorkflowFinishedMessage.EventName)]
    public virtual Task HandleMessageAsync(TemplateWorkflowFinishedMessage message, CancellationToken cancellationToken)
    {
        return HandleAsync(message, cancellationToken);
    }
}
