// <Auto-Generated/>
using DotNetCore.CAP;
using TemplateNamespace.Message;

namespace TemplateNamespace.Internal;

partial class TemplateWorkflowStateMachineDriverBase : ICapSubscribe
{
    /// <summary>
    /// 处理消息 <inheritdoc cref="TemplateWorkflowFailureMessage.EventName"/>
    /// </summary>
    /// <param name="message"></param>
    /// <param name="cancellationToken"></param>
    /// <returns></returns>
    [CapSubscribe(TemplateWorkflowFailureMessage.EventName)]
    public virtual Task HandleMessageAsync(TemplateWorkflowFailureMessage message, CancellationToken cancellationToken)
    {
        return HandleAsync(message, cancellationToken);
    }

    /// <summary>
    /// 处理消息 <inheritdoc cref="TemplateWorkflowStage1CAUKStageCompletedMessage.EventName"/>
    /// </summary>
    /// <param name="message"></param>
    /// <param name="cancellationToken"></param>
    /// <returns></returns>
    [CapSubscribe(TemplateWorkflowStage1CAUKStageCompletedMessage.EventName)]
    public virtual Task HandleMessageAsync(TemplateWorkflowStage1CAUKStageCompletedMessage message, CancellationToken cancellationToken)
    {
        return HandleAsync(message, cancellationToken);
    }

    /// <summary>
    /// 处理消息 <inheritdoc cref="TemplateWorkflowStage2BPTGStageCompletedMessage.EventName"/>
    /// </summary>
    /// <param name="message"></param>
    /// <param name="cancellationToken"></param>
    /// <returns></returns>
    [CapSubscribe(TemplateWorkflowStage2BPTGStageCompletedMessage.EventName)]
    public virtual Task HandleMessageAsync(TemplateWorkflowStage2BPTGStageCompletedMessage message, CancellationToken cancellationToken)
    {
        return HandleAsync(message, cancellationToken);
    }

    /// <summary>
    /// 处理消息 <inheritdoc cref="TemplateWorkflowStage3AWBNStageCompletedMessage.EventName"/>
    /// </summary>
    /// <param name="message"></param>
    /// <param name="cancellationToken"></param>
    /// <returns></returns>
    [CapSubscribe(TemplateWorkflowStage3AWBNStageCompletedMessage.EventName)]
    public virtual Task HandleMessageAsync(TemplateWorkflowStage3AWBNStageCompletedMessage message, CancellationToken cancellationToken)
    {
        return HandleAsync(message, cancellationToken);
    }
}
