// <Auto-Generated/>

using DotNetCore.CAP;
using TemplateNamespace.Template.Message;

namespace TemplateNamespace.Template.Handler;

partial class TemplateResultObserver : ICapSubscribe
{
    /// <summary>
    /// 处理消息 <inheritdoc cref="TemplateFinishedMessage.EventName"/>
    /// </summary>
    /// <param name="message"></param>
    /// <param name="cancellationToken"></param>
    /// <returns></returns>
    [CapSubscribe(TemplateFinishedMessage.EventName)]
    public virtual Task HandleMessageAsync(TemplateFinishedMessage message, CancellationToken cancellationToken)
    {
        return HandleAsync(message, cancellationToken);
    }
}
