// <Auto-Generated/>

using MessagePack;

namespace FluentWorkflow.Management.Shared.Messages.Abstractions;

/// <summary>
/// 分页请求
/// </summary>
/// <typeparam name="TQuery"></typeparam>
[MessagePackObject]
public record PagingRequest<TQuery>
{
    /// <summary>
    /// 页码
    /// </summary>
    [Key(0)]
    public required int Page { get; set; }

    /// <summary>
    /// 页大小
    /// </summary>
    [Key(1)]
    public required int PageSize { get; set; }

    /// <summary>
    /// 查询内容
    /// </summary>
    [Key(2)]
    public TQuery? Query { get; set; }

    /// <summary>
    /// 计算后的跳过数量
    /// </summary>
    [IgnoreMember]
    public int Skip => (Page - 1) * PageSize;
}

/// <summary>
/// 分页响应
/// </summary>
/// <typeparam name="TItem"></typeparam>
[MessagePackObject]
public record PagedResponse<TItem>
{
    /// <summary>
    /// 总数量
    /// </summary>
    [Key(0)]
    public required int? TotalCount { get; set; }

    /// <summary>
    /// 数据项列表
    /// </summary>
    [Key(1)]
    public required IList<TItem> Items { get; set; }
}
