// <Auto-Generated/>

// 源代码生成器初始化的标记类型集合

// 已定义无声明标记类型时不添加
#if !NO_FLUENTWORKFLOW_DECLARATION_MARKER_TYPES

#pragma warning disable IDE0130

namespace FluentWorkflow;

#region interfaces

/// <summary>
/// 工作流程声明接口，声明当前类型将要描述一个工作流程
/// </summary>
internal interface IWorkflowDeclaration
{
}

#endregion interfaces

#endif
