// <Auto-Generated/>
using Microsoft.Extensions.DependencyInjection;
using TemplateNamespace.Message;
using Volo.Abp.EventBus.Distributed;
using Volo.Abp.Threading;

namespace TemplateNamespace.Handler;

partial class TemplateWorkflowResultObserver : IDistributedEventHandler<TemplateWorkflowFinishedMessage>
{
    /// <summary>
    /// Abp 的 <see cref="ICancellationTokenProvider"/>
    /// </summary>
    protected ICancellationTokenProvider? CancellationTokenProvider => ServiceProvider.GetService<ICancellationTokenProvider>();

    /// <summary>
    /// 处理消息 - <see cref="TemplateWorkflowFinishedMessage"/>
    /// </summary>
    /// <param name="eventData"></param>
    /// <returns></returns>
    public virtual Task HandleEventAsync(TemplateWorkflowFinishedMessage eventData)
    {
        return HandleAsync(eventData, CancellationTokenProvider?.Token ?? default);
    }
}
