// <Auto-Generated/>
using Volo.Abp.EventBus;

namespace TemplateNamespace.Message;

[EventName(EventName)]
partial class TemplateWorkflowStartRequestMessage { }

[EventName(EventName)]
partial class TemplateWorkflowFinishedMessage { }

[EventName(EventName)]
partial class TemplateWorkflowFailureMessage { }

[EventName(EventName)]
partial class TemplateWorkflowStage1CAUKStageMessage { }

[EventName(EventName)]
partial class TemplateWorkflowStage1CAUKStageCompletedMessage { }

[EventName(EventName)]
partial class TemplateWorkflowStage2BPTGStageMessage { }

[EventName(EventName)]
partial class TemplateWorkflowStage2BPTGStageCompletedMessage { }

[EventName(EventName)]
partial class TemplateWorkflowStage3AWBNStageMessage { }

[EventName(EventName)]
partial class TemplateWorkflowStage3AWBNStageCompletedMessage { }
