// <Auto-Generated/>
using Microsoft.Extensions.DependencyInjection;
using TemplateNamespace.Template.Message;
using Volo.Abp.EventBus.Distributed;
using Volo.Abp.Threading;

namespace TemplateNamespace.Template.Handler;

partial class StageStage1CAUKHandlerBase : IDistributedEventHandler<StageStage1CAUKMessage>
{
    /// <summary>
    /// Abp 的 <see cref="ICancellationTokenProvider"/>
    /// </summary>
    protected ICancellationTokenProvider? CancellationTokenProvider => ServiceProvider.GetService<ICancellationTokenProvider>();

    /// <summary>
    /// 处理消息 - <see cref="StageStage1CAUKMessage"/>
    /// </summary>
    /// <param name="eventData"></param>
    /// <returns></returns>
    public virtual Task HandleEventAsync(StageStage1CAUKMessage eventData)
    {
        return HandleAsync(eventData, CancellationTokenProvider?.Token ?? default);
    }
}

partial class StageStage2BPTGHandlerBase : IDistributedEventHandler<StageStage2BPTGMessage>
{
    /// <summary>
    /// Abp 的 <see cref="ICancellationTokenProvider"/>
    /// </summary>
    protected ICancellationTokenProvider? CancellationTokenProvider => ServiceProvider.GetService<ICancellationTokenProvider>();

    /// <summary>
    /// 处理消息 - <see cref="StageStage2BPTGMessage"/>
    /// </summary>
    /// <param name="eventData"></param>
    /// <returns></returns>
    public virtual Task HandleEventAsync(StageStage2BPTGMessage eventData)
    {
        return HandleAsync(eventData, CancellationTokenProvider?.Token ?? default);
    }
}

partial class StageStage3AWBNHandlerBase : IDistributedEventHandler<StageStage3AWBNMessage>
{
    /// <summary>
    /// Abp 的 <see cref="ICancellationTokenProvider"/>
    /// </summary>
    protected ICancellationTokenProvider? CancellationTokenProvider => ServiceProvider.GetService<ICancellationTokenProvider>();

    /// <summary>
    /// 处理消息 - <see cref="StageStage3AWBNMessage"/>
    /// </summary>
    /// <param name="eventData"></param>
    /// <returns></returns>
    public virtual Task HandleEventAsync(StageStage3AWBNMessage eventData)
    {
        return HandleAsync(eventData, CancellationTokenProvider?.Token ?? default);
    }
}
