// <Auto-Generated/>
using Microsoft.Extensions.DependencyInjection;
using TemplateNamespace.Message;
using Volo.Abp.EventBus.Distributed;
using Volo.Abp.Threading;

namespace TemplateNamespace.Handler;

partial class TemplateWorkflowStage1CAUKStageHandlerBase : IDistributedEventHandler<TemplateWorkflowStage1CAUKStageMessage>
{
    /// <summary>
    /// Abp 的 <see cref="ICancellationTokenProvider"/>
    /// </summary>
    protected ICancellationTokenProvider? CancellationTokenProvider => ServiceProvider.GetService<ICancellationTokenProvider>();

    /// <summary>
    /// 处理消息 - <see cref="TemplateWorkflowStage1CAUKStageMessage"/>
    /// </summary>
    /// <param name="eventData"></param>
    /// <returns></returns>
    public virtual Task HandleEventAsync(TemplateWorkflowStage1CAUKStageMessage eventData)
    {
        return HandleAsync(eventData, CancellationTokenProvider?.Token ?? default);
    }
}

partial class TemplateWorkflowStage2BPTGStageHandlerBase : IDistributedEventHandler<TemplateWorkflowStage2BPTGStageMessage>
{
    /// <summary>
    /// Abp 的 <see cref="ICancellationTokenProvider"/>
    /// </summary>
    protected ICancellationTokenProvider? CancellationTokenProvider => ServiceProvider.GetService<ICancellationTokenProvider>();

    /// <summary>
    /// 处理消息 - <see cref="TemplateWorkflowStage2BPTGStageMessage"/>
    /// </summary>
    /// <param name="eventData"></param>
    /// <returns></returns>
    public virtual Task HandleEventAsync(TemplateWorkflowStage2BPTGStageMessage eventData)
    {
        return HandleAsync(eventData, CancellationTokenProvider?.Token ?? default);
    }
}

partial class TemplateWorkflowStage3AWBNStageHandlerBase : IDistributedEventHandler<TemplateWorkflowStage3AWBNStageMessage>
{
    /// <summary>
    /// Abp 的 <see cref="ICancellationTokenProvider"/>
    /// </summary>
    protected ICancellationTokenProvider? CancellationTokenProvider => ServiceProvider.GetService<ICancellationTokenProvider>();

    /// <summary>
    /// 处理消息 - <see cref="TemplateWorkflowStage3AWBNStageMessage"/>
    /// </summary>
    /// <param name="eventData"></param>
    /// <returns></returns>
    public virtual Task HandleEventAsync(TemplateWorkflowStage3AWBNStageMessage eventData)
    {
        return HandleAsync(eventData, CancellationTokenProvider?.Token ?? default);
    }
}
