// <Auto-Generated/>
using Microsoft.Extensions.DependencyInjection;
using TemplateNamespace.Message;
using Volo.Abp.EventBus.Distributed;
using Volo.Abp.Threading;

namespace TemplateNamespace.Internal;

partial class TemplateWorkflowStateMachineDriverBase
   : IDistributedEventHandler<TemplateWorkflowFailureMessage>
   , IDistributedEventHandler<TemplateWorkflowStage1CAUKStageCompletedMessage>
   , IDistributedEventHandler<TemplateWorkflowStage2BPTGStageCompletedMessage>
   , IDistributedEventHandler<TemplateWorkflowStage3AWBNStageCompletedMessage>
{
    private ICancellationTokenProvider? _cancellationTokenProvider;

    private ICancellationTokenProvider CancellationTokenProvider => _cancellationTokenProvider ??= ServiceProvider.GetRequiredService<ICancellationTokenProvider>();

    /// <summary>
    /// 处理消息 - <see cref="TemplateWorkflowFailureMessage"/>
    /// </summary>
    /// <param name="eventData"></param>
    /// <returns></returns>
    public virtual Task HandleEventAsync(TemplateWorkflowFailureMessage eventData)
    {
        var cancellationToken = CancellationTokenProvider.Token;
        return HandleAsync(eventData, cancellationToken);
    }

    /// <summary>
    /// 处理消息 - <see cref="TemplateWorkflowStage1CAUKStageCompletedMessage"/>
    /// </summary>
    /// <param name="eventData"></param>
    /// <returns></returns>
    public virtual Task HandleEventAsync(TemplateWorkflowStage1CAUKStageCompletedMessage eventData)
    {
        var cancellationToken = CancellationTokenProvider.Token;
        return HandleAsync(eventData, cancellationToken);
    }

    /// <summary>
    /// 处理消息 - <see cref="TemplateWorkflowStage2BPTGStageCompletedMessage"/>
    /// </summary>
    /// <param name="eventData"></param>
    /// <returns></returns>
    public virtual Task HandleEventAsync(TemplateWorkflowStage2BPTGStageCompletedMessage eventData)
    {
        var cancellationToken = CancellationTokenProvider.Token;
        return HandleAsync(eventData, cancellationToken);
    }

    /// <summary>
    /// 处理消息 - <see cref="TemplateWorkflowStage3AWBNStageCompletedMessage"/>
    /// </summary>
    /// <param name="eventData"></param>
    /// <returns></returns>
    public virtual Task HandleEventAsync(TemplateWorkflowStage3AWBNStageCompletedMessage eventData)
    {
        var cancellationToken = CancellationTokenProvider.Token;
        return HandleAsync(eventData, cancellationToken);
    }
}
