// <Auto-Generated/>
using Volo.Abp.EventBus;

namespace TemplateNamespace.Template.Message;

[EventName(EventName)]
partial class TemplateStartRequestMessage { }

[EventName(EventName)]
partial class TemplateFinishedMessage { }

[EventName(EventName)]
partial class TemplateFailureMessage { }

[EventName(EventName)]
partial class StageStage1CAUKMessage { }

[EventName(EventName)]
partial class StageStage1CAUKCompletedMessage { }

[EventName(EventName)]
partial class StageStage2BPTGMessage { }

[EventName(EventName)]
partial class StageStage2BPTGCompletedMessage { }

[EventName(EventName)]
partial class StageStage3AWBNMessage { }

[EventName(EventName)]
partial class StageStage3AWBNCompletedMessage { }
