// <Auto-Generated/>

using Microsoft.Extensions.DependencyInjection;
using TemplateNamespace.Template.Message;
using Volo.Abp.EventBus.Distributed;
using Volo.Abp.Threading;

namespace TemplateNamespace.Template.Handler;

partial class TemplateStartRequestHandler<TWorkflow> : IDistributedEventHandler<TemplateStartRequestMessage>
{
    /// <summary>
    /// 处理消息 - <see cref="TemplateStartRequestMessage"/>
    /// </summary>
    /// <param name="eventData"></param>
    /// <returns></returns>
    public virtual Task HandleEventAsync(TemplateStartRequestMessage eventData)
    {
        return HandleAsync(eventData, ServiceProvider.GetService<ICancellationTokenProvider>()?.Token ?? default);
    }
}
